### ISSUE TITLE
PHP 7.2.x

### ISSUE THREAD

**Issue by SylvainLegrand** [elijaa/phpmemcachedadmin#43]
Warning with PHP 7.2.x => "PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in C:\wamp\apps\phpmemcachedadmin\Library\Bootstrap.php on line 20"

How to correct that ?

Greetings,
Sylvain Legrand

**Comment by afraazali** [comment]
I was facing the same issue on 7.1.18. You should be able to add the following code under the `__autoload` function:

```
spl_autoload_register('__autoload');
```

There's warnings on the next page, however it is working properly.

**Comment by fgm** [comment]
Send PR #45 for this. Also sent to alphalyax repo, since this is the one pointed to by Packagist (why is it not this one ?)

**Comment by LuzRain** [comment]
You should just replace this in file /Library/Bootstrap.php:
```
# Autoloader
function __autoload($class)
{
    require_once str_replace('_', DIRECTORY_SEPARATOR, $class) . '.php';
}
```
to this:
```
# Autoloader
spl_autoload_register(function ($class) {
    require_once str_replace('_', DIRECTORY_SEPARATOR, $class) . '.php';
});
```

**Comment by fgm** [comment]
@LuzRain AIUI, phpmemcacheadmin is supposed to work with versions of PHP even older than PHP 5.3.0 which introduced anonymous functions, so this syntax wouldn't be allowable. spl_autoload_register was introduced in 5.1.0, which appears to be fine.

**Comment by sonyarianto** [comment]
For me it's run fine on my 7.2.8

**Comment by fgm** [comment]
@SylvainLegrand would you mind closing this issue since the fix has been merged since last summer ? Or is there any remaining problem ?
